ROOT_DIR := $(realpath ../..)
include $(ROOT_DIR)/config.mk

all:
	$(MAKE) -C hipvadd


run-simx:
	$(MAKE) -C hipvadd run-simx


run-rtlsim:
	$(MAKE) -C hipvadd run-rtlsim


clean:
	$(MAKE) -C hipvadd clean
